language: node_js
node_js:
  - 'stable'
install:
  - yarn
  - npm install coveralls
script: 'yarn test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
notifications:
  email: false
