version: '3.9'

services:
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3316:3306
    container_name: nukak-mysql-8

  mariadb:
    image: yobasystems/alpine-mariadb:10.6.9
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - 3326:3306
    container_name: nukak-mariadb-10

  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 5442:5432
    container_name: nukak-postgres-14
