version: '3.4'

services:
  mysql:
    image: 'mysql:8.0.21'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - '3306:3306'
    container_name: 'onql-mysql-8'
  postgres-9:
    image: postgres:9.6.18
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    container_name: onql-postgres-9
  # Managed with 'run-rs' package
  # mongodb:
  #   image: 'mongo:4.4.0'
  #   container_name: 'onql-mongodb-4'
  #   ports:
  #     - '27017:27017'
  # postgres-12:
  #   image: postgres:12.3
  #   environment:
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: test
  #   ports:
  #     - '5433:5432'
  #   container_name: onql-postgres-12
