version: '3.4'

services:
  mysql:
    image: 'mysql:8.0.25'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - '3307:3306'
    container_name: 'uql-mysql-8'
    
  mariadb:
    image: 'mariadb:10.5.10'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test'
    ports:
      - '3310:3306'
    container_name: 'uql-mariadb-10'

  postgres-13:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    container_name: uql-postgres-13
